### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-block_my_enrolled_courses#4]
We have noticed one thing that Course name formatting is missing. In block {mlang} tag is showing instead of converting it to particular language.
Eg: {mlang en}Test Course - 08.02.22(EN){mlang}{mlang fr}Test Course - 08.02.22(FR){mlang}

Solution:
1. Go to line no. 128, 164, 192 in this path /blocks/my_enrolled_courses/locallib.php
2. Add format_string() whereever we are showing course fullname.
Example: $anchor = html_writer::link($url, format_string($courses[$id]->fullname));

Kindly verify it and update the code.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
